### ISSUE TITLE
Meant for updates too?

### ISSUE THREAD

**Issue by rept** [getkuby/kuby-core#21]
Is Kuby meant for updates too?  Let me explain: in our current setup we have a cluster with Postgres, Nginx, Redis, Ruby etc...

Tagging a commit automatically starts of Jenkins that builds the new image.  This image is pushed to Docker hub and then pushed to staging.  This spins up a second Ruby pod and as soon as the liveness and readinessProbe of that pod is OK it shuts down the old pod.  Works fantastic.

Your tutorial and video clearly explain how you can easily spin up a complete cluster that even takes care of the certificates.  But is Kuby aimed at doing updates (to the Ruby pod) later on too?  

Something like:

    bundle exec kuby -e production update

Since you know the port of each pod you could include a liveness and readinessProbe to do the basic checks on the ports.

These are the probes we currently use for our Ruby pod. 

```
        livenessProbe:
          httpGet:
            path: /
            port: 80
          # Give the node some time to startup. Replace by startupProbe once it leaves alpha state.
          initialDelaySeconds: 180
          failureThreshold: 2
          periodSeconds: 40
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          timeoutSeconds: 2
```
