### ISSUE TITLE
Support using a user other than root to connect to databases

### ISSUE THREAD

**Issue by camertron** [getkuby/kuby-core#46]
I discovered yesterday that `rails new mytestapp -d mysql` will create a database.yml file with the `username` field set to the name of the app, eg:

```yaml
production:
  adapter: mysql2
  username: mytestapp
  password: <%= ENV['MYTESTAPP_DATABASE_PASSWORD'] %>
```

All the rails apps I tested while developing Kuby use the `root` user, which kubedb creates by default. I assumed kubedb would create a user from whatever username and password you give it, but that is definitely not the case. Kubedb has the ability to run an init script when MySQL and Postgres instances start, so I think that's the vector we need to use to get the user created (if it isn't `root`).
