### ISSUE TITLE
Error: uninitialized constant Kuby::KubeDB with Sidekiq or Redis gems

### ISSUE THREAD

**Issue by scart88** [getkuby/kuby-core#98]
Adding Sidekiq or Redis are resulting with the following error:
```
RAILS_MASTER_KEY=some-key bundle exec kuby -e production deploy
Error: uninitialized constant Kuby::KubeDB
```

### Gemfile
```
gem "kuby-redis", "~> 0.1.0"
gem "kuby-sidekiq", "~> 0.3.0"
```

### kuby.rb file
```
kubernetes do
      ***
      
      add_plugin :redis do
        instance(:my_rails_cache)
      end
      
      add_plugin :sidekiq
end
```

**Comment by scart88** [comment]
I thought it was not required to run `bundle exec kuby -e production setup` again. But, I guess it is required. I will try again tomorrow.  

Thanks for everything!

**Comment by scart88** [comment]
Could we use something like this https://keydb.dev/ ?

**Comment by scart88** [comment]
Or wouldn't be possible to use some YAML files like these?

### redis.yml
```yml
apiVersion: v1
kind: Service
metadata:
  name: app-redis-svc
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: app-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-redis
spec:
  selector:
    matchLabels:
      app: app-redis
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app-redis
    spec:
      containers:
        - name: redis
          image: redis:5.0-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 500Mi
          volumeMounts:
            - mountPath: /data
              name: app-redis-data
      volumes:
        - name: app-redis-data
          emptyDir: {}
```

### sidekiq.yml
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sidekiq
spec:
  selector:
    matchLabels:
      app: app-sidekiq
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: app-sidekiq
    spec:
      imagePullSecrets:
        - name: digitalocean-access-token
      containers:
        - name: sidekiq
          image: $IMAGE_TAG
          imagePullPolicy: Always
          command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
          env:
          - name: RAILS_ENV
            value: "production"
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: REDIS_URL
            value: "redis://app-redis-svc:6379"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: app-master-key
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 1100m
              memory: 1100Mi
          ports:
            - containerPort: 7433
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 2
            failureThreshold: 2
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["k8s/sidekiq_quiet"]
      terminationGracePeriodSeconds: 300
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: app-sidekiq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-sidekiq
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
```


Even with these YAML files, I wouldn't know how to use them with Kuby.

**Comment by camertron** [comment]
Hey @scart88, thanks for letting me know about this. Unfortunately I haven't had the chance to upgrade the kuby-redis gem to the version of KubeDB that kuby-core uses, so that's why you're seeing the issues with the `Redis` object type. Future versions of Kuby won't even use KubeDB because they've moved to an incompatible licensing model.

Unfortunately I don't have a workaround for you on this one. Don't get me wrong, I would love to support all this in the hopefully not too distant future.

> Even with these YAML files, I wouldn't know how to use them with Kuby.

Yeah, Kuby doesn't support custom YAML files, although that might be a cool feature to add someday.

**Comment by scart88** [comment]
Thank you very much. Having a managed redis or a simple self-managed redis on a vps seems to be a better option.

It looks like kuby is already supporting YAML files: `bundle exec kuby -e production kubectl -- apply -f k8s/ingress.yaml....`

**Comment by camertron** [comment]
Oh that's true, you can use `kubectl` directly via the Kuby CLI. I just meant there's not a way to ask Kuby to deploy custom YAMLs at the same time it deploys everything else.

**Comment by scart88** [comment]
Hey @camertron, I hope you are doing well.

I found these 2 options to use instead of KubeDB. Is there any reason why these are not good options for Kuby?

Redis: https://artifacthub.io/packages/helm/bitnami/redis
Postgresql: https://access.crunchydata.com/documentation/postgres-operator/v5/

Thanks

**Comment by camertron** [comment]
Hey @scart88. I missed your comment about KeyDB, looks really interesting :) If it's Redis-compatible then it could be a replacement worth considering.

Ah yeah, I've seen both the Bitnami Redis helm chart and the Crunchy Postgres operator. I considered using the Postgres operator for a while, but settled on CockroachDB because it's designed to work in cloud-native environments whereas Postgres is not. CockroachDB can be upgraded in-place and provides all these nice guarantees. It's nearly 100% compatible with Postgres, so it seemed like the right way to go.

It turns out to be much easier to run a Redis instance, so a Helm chart or just a regular 'ol k8s statefulset should work. The one you linked to may indeed be what Kuby ends up using :)

**Comment by denikus** [comment]
@scart88 Did you manage to deploy and use sidekiq with selfhosted redis? I would appreciate if you share you solution for this case. Still have a problem to run sidekiq with kuby (

**Comment by scart88** [comment]
Hey @denikus 

Yes, I used `bitnami/redis` https://artifacthub.io/packages/helm/bitnami/redis.

You will need to have a PersistentVolume, and in my case I used `storageClass: "do-block-storage"` since I'm using DigitalOcean. You will need to configure your redis helm values, add your `password`, your `storageClass`, set your replica count, add your resources limits, etc...

I also used a PersistentVolume size of 1Gb for the master, and 1Gb for the replicas. If you have 1 master and 3 replicas, helm will generate 4 PersistentVolumeClaims on your storage. The default is 8Gb, so you might want to change that.

I discovered https://k8slens.dev/ which a great tool to see and manage your cluster, and it's open-source. You don't even need an account.

Here you can see all available bitnami/redis values you can change:
https://artifacthub.io/packages/helm/bitnami/redis?modal=values

```
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "do-block-storage"
  redis:
    password: "your-very-strong-password"
```

```
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests: {}
      cpu: 100m
      memory: 128Mi
```

Once you setup redis, you can access it from other pods inside your cluster. The default username is `default` and the password is what you set in the global.
`redis://default:your-password@redis-master.default.svc.cluster.local:6379/0`

I added my Redis url inside Rails credentials and I created a `sidekiq.rb` initializer.

### config/initializers/sidekiq.rb
```ruby
sidekiq_url = if Rails.env.production?
  Rails.application.credentials.dig(:production, :REDIS_URL) ||  "redis://localhost:6379/1"
else 
  "redis://localhost:6379/1"
end


Sidekiq.configure_server do |config|
  config.redis = { url: sidekiq_url }
end

Sidekiq.configure_client do |config|
  config.redis = { url: sidekiq_url }
end
```

### I also changed my `cable.yml` file
```
production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:production, :REDIS_URL) ||  "redis://localhost:6379/1" %>
```

If you are using `hiredis` and `cache_store` you will need to use the same REDIS_URL in your:
### development.rb or production.rb
```ruby
config.cache_store = :redis_cache_store, {driver: :hiredis, url: Rails.application.credentials[:REDIS_URL] || "redis://localhost:6379/1" }
config.session_store :redis_session_store, key: "_session_app_production", serializer: :json,
  redis: {
    driver: :hiredis,
    expire_after: 1.year,
    ttl: 1.year,
    url: Rails.application.credentials[:REDIS_URL] || "redis://localhost:6379/6"
  }
```

At this step, you should have Redis configured and ready to use on your cluster.
Now, you will need to deploy the `sidekiq worker`. 
Unfortunately I wasn't able to deploy it with Kuby, so I used a custom yaml file. 

### sidekiq.yml
And you would install it like this: `kubectl apply -f sidekiq.yml`, however you will need to make this compatible with your app, cluster, namespace, etc... This is just an example.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: your-app-namespace
  labels:
    role: worker
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: app-worker
      role: web
  template:
    metadata:
      labels:
        app: app-worker
    spec:
      containers:
      - name: app-worker
        image: your-registry-url
        imagePullPolicy: Always
        command: ["launcher"]
        args: ["bundle", "exec", "sidekiq"]
        envFrom:
        - configMapRef:
            name: env
        - secretRef:
            name: your-app-secrets
        env:
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1000Mi" 
      initContainers:
      - name: migration-check
        image: your-registry-url
        imagePullPolicy: Always
        command: ["launcher"]
        args: ["rake", "db:abort_if_pending_migrations"]
        envFrom:
        - configMapRef:
            name: env # for example app-example-config
        - secretRef:
            name: your-app-secrets # for example app-example-secrets
      imagePullSecrets:
      - name: your-reg-secrets
```

You can run `bundle exec kuby -e production resources`, look for Deployment pod with the role web, duplicate it and make it look like in my previous example.

Maybe @camertron can help a little bit more with the sidekiq.yml file and how can it be configured directly inside `kuby.rb file`

I hope it make sense.
